basePath: /
definitions:
  handlers.OutputGetFinances:
    properties:
      amount:
        type: number
      date:
        type: string
      status:
        type: string
    type: object
  handlers.OutputGetFinancesFailure:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact:
    email: danielsantos120615@gmail.com
    name: Daniel lucas
  description: This is an example of an api using swagger
  title: Finances example api
  version: v0.0.1
paths:
  /finances:
    get:
      description: Get finances
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.OutputGetFinances'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.OutputGetFinancesFailure'
      security:
      - ApiKeyAuth: []
      summary: Get finances
      tags:
      - finances
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
